---
language: python

install:
  - pip install -r test-requirements.txt

script:
  - yamllint -c .yamllint.yml etc/images.yml .yamllint.yml .yamale.yml
  - yamale -s .yamale.yml -p ruamel etc/images.yml
  - flake8 --ignore E501,F821
